ruby '2.3.0'
source 'https://rubygems.org'

gem 'sinatra'
gem 'rest-client'
gem 'rack-test', require: 'rack/test'
gem 'rspec'
gem 'rspec-its'
gem 'byebug'
gem 'pact'
gem 'rake'
gem 'pact_broker-client'